export const works = [
    {
        slug: "the-refill-stop",
        title: "The Refill Stop",
        link: "https://www.therefillstop.com/",
        description: "En mi experiencia trabajando en **The Refill Stop**, participé en el desarrollo de una plataforma e-commerce enfocada en la venta de productos sustentables para el hogar. **Mi principal desafío** fue crear una experiencia de usuario fluida y atractiva, destacando el compromiso de la tienda con la **sostenibilidad**. Implementé funcionalidades clave para facilitar la navegación y el proceso de compra, optimizando el rendimiento del sitio y asegurando su accesibilidad. También integré soluciones que resaltaran los beneficios ecológicos de los productos, ayudando a comunicar la misión de reducir el uso de plásticos y promover un estilo de vida más responsable.",
        jobDone: [
            "Responsive Design",
            "Frontend Development",
            "React",
            "Tailwind",
            "Javascript",
            "Astro",
            "Nanostores",
            "Figma",
            "UX",
            "Framer Motion"
        ],
        miniature: "/media/therefillstop/miniature.png",
        desktopShowcase: "/media/therefillstop/desktop-showcase.png",
        mobileShowcase: "/media/therefillstop/mobile-showcase.png",
        fullpageShowcase: "/media/therefillstop/fullpage-showcase.png",
        date: "2024",
        type: "e-Commerce",
        typeOfWork: "Freelance",
    },
    {
        slug: "balance-boost",
        title: "Balance Boost",
        link: "",
        description: "En mi experiencia trabajando en **The Refill Stop**, participé en el desarrollo de una plataforma e-commerce enfocada en la venta de productos sustentables para el hogar. Mi principal desafío fue crear una experiencia de usuario fluida y atractiva, destacando el compromiso de la tienda con la sostenibilidad. Implementé funcionalidades clave para facilitar la navegación y el proceso de compra, optimizando el rendimiento del sitio y asegurando su accesibilidad. También integré soluciones que resaltaran los beneficios ecológicos de los productos, ayudando a comunicar la misión de reducir el uso de plásticos y promover un estilo de vida más responsable.",
        jobDone: [
            "Responsive Design",
            "Frontend Development",
            "React",
            "Tailwind",
            "Typescript",
            "Astro",
            "Nanostores",
            "Figma",
            "UX",
            "Swiper.js"
        ],
        miniature: "/media/balanceboost/miniature.png",
        desktopShowcase: "/media/balanceboost/desktop-showcase.png",
        mobileShowcase: "/media/balanceboost/mobile-showcase.png",
        fullpageShowcase: "/media/balanceboost/fullpage-showcase.png",
        date: "2024",
        type: "e-Commerce",
        typeOfWork: "Freelance",
    },
    {
        slug: "starfish",
        title: "Starfish",
        link: "",
        description: "En mi experiencia trabajando en **The Refill Stop**, participé en el desarrollo de una plataforma e-commerce enfocada en la venta de productos sustentables para el hogar. Mi principal desafío fue crear una experiencia de usuario fluida y atractiva, destacando el compromiso de la tienda con la sostenibilidad. Implementé funcionalidades clave para facilitar la navegación y el proceso de compra, optimizando el rendimiento del sitio y asegurando su accesibilidad. También integré soluciones que resaltaran los beneficios ecológicos de los productos, ayudando a comunicar la misión de reducir el uso de plásticos y promover un estilo de vida más responsable.",
        jobDone: [
            "Responsive Design",
            "Frontend Development",
            "React",
            "Tailwind",
            "Typescript",
            "Astro",
            "Nanostores",
            "Figma",
            "UX",
            "Swiper.js"
        ],
        miniature: "/media/starfish/miniature.png",
        desktopShowcase: "/media/starfish/desktop-showcase.png",
        mobileShowcase: "/media/starfish/mobile-showcase.png",
        fullpageShowcase: "/media/starfish/fullpage-showcase.png",
        date: "2024",
        type: "e-Commerce",
        typeOfWork: "Freelance",
    },
]