export const works = [
    {
        slug: "the-refill-stop",
        title: "The Refill Stop",
        link: "https://www.therefillstop.com/",
        description: "En mi experiencia trabajando en **The Refill Stop**, participé en el desarrollo de una plataforma e-commerce enfocada en la venta de productos sustentables para el hogar. **Mi principal desafío** fue crear una experiencia de usuario fluida y atractiva, destacando el compromiso de la tienda con la **sostenibilidad**. Implementé funcionalidades clave para facilitar la navegación y el proceso de compra, optimizando el rendimiento del sitio y asegurando su accesibilidad. También integré soluciones que resaltaran los beneficios ecológicos de los productos, ayudando a comunicar la misión de reducir el uso de plásticos y promover un estilo de vida más responsable.",
        jobDone: [
            "HTML",
            "CSS",
            "Responsive Design",
            "Frontend Development",
            "React",
            "Tailwind",
            "Javascript",
            "Astro",
            "Nanostores",
            "Figma",
            "UX",
            "Framer Motion"
        ],
        miniature: "/media/therefillstop/miniature.png",
        desktopShowcase: "/media/therefillstop/desktop-showcase.png",
        mobileShowcase: "/media/therefillstop/mobile-showcase.png",
        fullpageShowcase: "/media/therefillstop/fullpage-showcase.png",
        date: "2024",
        type: "e-Commerce",
        typeOfWork: "Freelance",
        techs: [
            "HTML",
            "CSS",
            "JavaScript",
            "React",
            "Tailwind",
            "Astro",
            "Nanostores",
            "Figma",
            "Framer Motion"
        ],
    },
    {
        slug: "balance-boost",
        title: "Balance Boost",
        link: "",
        description: "Colaboré con un cliente en el diseño de un mockup para la página web **Balance Boost**, enfocada en la promoción de suplementos dietéticos. El proyecto se centró en crear una estética profesional alineada con los valores de salud y bienestar, desarrollando una **interfaz moderna** que incluyó una landing page atractiva, un catálogo de productos, un blog informativo y una página de contacto. También optimicé la experiencia del usuario para facilitar la navegación y destacar información clave, con el objetivo de maximizar las conversiones.",
        jobDone: [
            "HTML",
            "CSS",
            "Responsive Design",
            "Frontend Development",
            "React",
            "Tailwind",
            "TypeScript",
            "Astro",
            "Nanostores",
            "Figma",
            "UX",
            "Swiper.js"
        ],
        miniature: "/media/balanceboost/miniature.png",
        desktopShowcase: "/media/balanceboost/desktop-showcase.png",
        mobileShowcase: "/media/balanceboost/mobile-showcase.png",
        fullpageShowcase: "/media/balanceboost/fullpage-showcase.png",
        date: "2024",
        type: "e-Commerce",
        typeOfWork: "Freelance",
        techs: [
            "HTML",
            "CSS",
            "TypeScript",
            "React",
            "Tailwind",
            "Astro",
            "Nanostores",
            "Figma",
            "Swiper.js"
        ],
    },
    {
        slug: "starfish",
        title: "Starfish",
        link: "",
        description: "En mi experiencia trabajando en **Starfish**, diseñé un mockup para una plataforma web dedicada a la venta de suplementos dietéticos de **base natural**. Mi principal desafío fue crear un diseño que transmitiera la esencia natural de los productos y reforzara el compromiso de la marca con el bienestar integral. Me enfoqué en desarrollar una experiencia de usuario intuitiva y atractiva, destacando la información clave de los productos para facilitar la toma de decisiones informadas. Además, creé dos landing pages adicionales enfocadas en la **promoción de productos específicos**, diseñadas para captar la atención del usuario y resaltar los beneficios exclusivos de cada suplemento. Propuse elementos visuales que reflejaran la conexión con la naturaleza, asegurando una estética coherente con los valores de la marca. El resultado fue un prototipo que combinó funcionalidad y diseño, potenciando la identidad única de Starfish.",
        jobDone: [
            "HTML",
            "CSS",
            "Responsive Design",
            "Frontend Development",
            "React",
            "Tailwind",
            "TypeScript",
            "Astro",
            "Nanostores",
            "Figma",
            "UX",
            "Swiper.js"
        ],
        miniature: "/media/starfish/miniature.png",
        desktopShowcase: "/media/starfish/desktop-showcase.png",
        mobileShowcase: "/media/starfish/mobile-showcase.png",
        fullpageShowcase: "/media/starfish/fullpage-showcase.png",
        date: "2024",
        type: "e-Commerce",
        typeOfWork: "Freelance",
        techs: [
            "HTML",
            "CSS",
            "TypeScript",
            "React",
            "Tailwind",
            "Astro",
            "Nanostores",
            "Figma",
            "Swiper.js"
        ],
    },
]